name: JaCaMo Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build
      run: ./gradlew build -x test -x compileTestJava
    
    - name: Run Java tests
      run: ./gradlew testJava

    - name: Run tests
      run: ./gradlew runAslTests